### ISSUE TITLE
Saving stacking

### ISSUE THREAD

**Issue by uzi0espil** [civisanalytics/civisml-extensions#30]
Is it possible to dump the stacking ensemble using joblib dump just as scikit-learn? will this store all the estimators within as well?

On another note, It would also be useful to have a save method where it will iterate through the estimators and store each one individually (should consider pipelines as well).

**Comment by beckermr** [comment]
Yes. The stacking estimator should pickle just fine. It has an attribute for accessing the individual estimators (`named_base_estimators`), so dumping them should be a loop

```python
for name, est in stk.named_estimators.items():
    with open(name + '.pkl', 'w') as fp:
        pickle.dump(est, fp)
```

You can dump the meta estimator using its attribute as well (`meta_estimator`).

My preference is to not have an extra method since it would have to make a lot of assumptions about file names, etc. 

Let me know if you have more questions.

**Comment by uzi0espil** [comment]
Thanks it worked. 
I think you are right about your reference. Cheers!
