### ISSUE TITLE
Compatibility with newest scikit-learn

### ISSUE THREAD

**Issue by stephen-hoover** [civisanalytics/civisml-extensions#45]
The requirements specify `scikit-learn>=0.18.1,<0.20`, and the newest release of scikit-learn is 0.20.2. Is this package incompatible with v0.20? If so, can we make it compatible with >=0.18.1? If it's already compatible, we should update the requirements.

**Comment by elsander** [comment]
We rely on a util that was removed from sklearn in 0.20, `check_fit1d_1feature`. Some relevant discussion (about public vs private utils in sklearn more generally) here: https://github.com/scikit-learn/scikit-learn/issues/6616.

I think the fix here would be to take the util code from an old version of sklearn and put it in civisml-extensions. Then we should be able to use newer versions without a problem.

**Comment by stephen-hoover** [comment]
> I think the fix here would be to take the util code from an old version of sklearn and put it in civisml-extensions. Then we should be able to use newer versions without a problem.

That sounds like a good fix. Thank you for tracking this down!

**Comment by elsander** [comment]
Ah, actually we import a bunch of estimator checks to test our estimator against the sklearn API. It seems that these checks aren't meant to be permanent parts of sklearn, they're internal utilities. Maybe we should be doing this using `sklearn.utils.estimator_checks.check_estimator`, although we have a list of known failing checks in there, so we'd fail that test :/

**Comment by elsander** [comment]
Not sure when we'll get to putting in a fix here, but there are other version compatibility issues that I uncovered that make this issue more annoying to fix. I'm documenting them here for the future.

* several hyperband tests fail on sklearn 0.19+ because the `.grid_scores_` attribute was deprecated in favor of `.cv_results_` for CV meta-estimators: https://github.com/scikit-learn/scikit-learn/pull/6697 https://scikit-learn.org/0.19/whats_new.html
* the `test_fit_with_nan_col` test fails on sklearn 0.20.2 (and possibly older versions, I haven't checked), for reasons I haven't determined yet. `DataFrameETL` doesn't issue a warning during fit as expected here.
* Multiple changes in which estimator checks exist cause import issues in `test_sklearn_api` `test_preprocessing.py`. `check_no_fit_attributes_set_in_init` is removed and both `check_fit1d_*` checks have been folded into a single `check_fit1d`. This should be fixable by removing the old checks and replacing the `check_fit1d_*1 with `check_fit1d`. We'll want to pin the dev-requirements version of sklearn and update it periodically, since the individual checks seem to be somewhat unstable.

**Comment by daveliu-riviera** [comment]
I love the Sklearn Interface for Hyperband and really appreciate you guys building it, but just disappointed that the sklearn version is so constrained right now. Wish I had time to make a pull request myself, but probably just going to have to find another package.

**Comment by elsander** [comment]
FYI @mheilman, I can take a stab at this for Hacktoberfest.

**Comment by daveliu-riviera** [comment]
I've been doing offline-training and unwrapping/pickling the best_estimator because this Hyperband Implementation is just so freaking good, but an updated integration would be SO much appreciated!
